### Create new preparation
POST http://localhost:8080/kitchen/preparation/create
content-type: application/json

{
  "name": "pizza di Petrone",
  "table": 1
}

### Get all preparations
GET http://localhost:8080/kitchen/preparations

### Change state of preparation
POST http://localhost:8080/kitchen/preparation/changeState
content-type: application/json

{
  "id": 1,
  "tableNum": 1,
  "state": "READY"
}

### Get all preparations
GET http://localhost:8080/waiter/preparations

### create new prep on waiter side
POST http://localhost:8080/waiter/preparation/create
content-type: application/json

{
  "name": "pizza di Petrone",
  "table": 1
}



