version: "3.2"
services:
  dbmariadb:
    container_name: mariadb
    image: "mariadb"
    ports:
      - "3306:3306"
    networks:
      - scavolini-network
      - scavolini-kitchen-internal
    environment:
      MARIADB_ROOT_PASSWORD: "root"
      MARIADB_USER: kitchen
      MARIADB_PASSWORD: kitchen
      MARIADB_DATABASE: scavolini-kitchen
    restart: unless-stopped
    volumes:
      - type: volume
        source: data-mariadb
        target: /data
        volume:
          nocopy: true
  app:
    build: .
    image: scavolini-kitchen
    container_name: scavolini-kitchen
    ports:
      - "8080:8080"
    depends_on:
      - dbmariadb
    networks:
      - scavolini-network
      - scavolini-kitchen-internal
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mariadb://mariadb:3306/scavolini-kitchen
      - SPRING_DATASOURCE_USERNAME=kitchen
      - SPRING_DATASOURCE_PASSWORD=kitchen
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

networks:
    scavolini-network:
    scavolini-kitchen-internal:

volumes:
    data-mariadb:
