version: "3.2"
services:
  dbmariadb:
    container_name: mariadb_waiter
    image: "mariadb"
    ports:
      - "3306:3306"
    networks:
      - scavolini-network
      - scavolini-waiter-internal
    environment:
      MARIADB_ROOT_PASSWORD: "root"
      MARIADB_USER: waiter
      MARIADB_PASSWORD: waiter
      MARIADB_DATABASE: waiter
    restart: unless-stopped
    volumes:
      - type: volume
        source: data-mariadb
        target: /data
        volume:
          nocopy: true
  waiter:
    build: .
    image: scavolini-waiter
    container_name: scavolini-waiter
    environment:
      MARIADB_HOST: mariadb_waiter
    ports:
      - "8080:8080"
    depends_on:
      - dbmariadb
    networks:
      - scavolini-network
      - scavolini-waiter-internal

networks:
  scavolini-network:
  scavolini-waiter-internal:

volumes:
  data-mariadb: