### Add dish
POST http://localhost:8080/menu/addDish
content-type: application/json

{
  "name": "Pollo alla cacciatora",
  "price": 12.99,
  "description": "Pollo alla cacciatora is a classic Italian dish of chicken braised in a tomato sauce with onions, garlic, herbs, and sometimes olives and capers. It is traditionally cooked in a casserole dish in the oven, but can also be made in a skillet on the stove top.",
  "course": "Secondo"
}

### Add list of dishes
POST http://localhost:8080/menu/addDishes
content-type: application/json

[
  {
    "name": "Pollo alla cacciatora",
    "price": 12.99,
    "description": "Pollo alla cacciatora is a classic Italian dish of chicken braised in a tomato sauce with onions, garlic, herbs, and sometimes olives and capers.",
    "course": "Primo"
  },
  {
    "name": "Risotto alla milanese",
    "price": 13.99,
    "description": "Risotto alla milanese is a classic Italian dish of rice cooked in a broth with saffron, butter, and grated Parmesan cheese.",
    "course": "Primo"
  },
  {
    "name": "Parmigiana di melanzane",
    "price": 14.99,
    "description": "Parmigiana di melanzane is a classic Italian dish of eggplant baked in a tomato sauce with mozzarella cheese.",
    "course": "Primo"
  },
  {
    "name": "Roast beef",
    "price": 15.99,
    "description": "Roast beef is a classic English dish of beef roasted in the oven. It is traditionally cooked in a casserole dish.",
    "course": "Secondo"
  },
  {
    "name": "Roast chicken",
    "price": 16.99,
    "description": "Roast chicken is a classic English dish of chicken roasted in the oven.",
    "course": "Secondo"
  },
  {
    "name": "English breakfast",
    "price": 17.99,
    "description": "English breakfast is a classic English dish of bacon, eggs, sausages, beans, mushrooms, tomatoes, and toast.",
    "course": "Colazione"
  },
  {
    "name": "Coppo di Vino",
    "price": 18.99,
    "description": "Coppo di Vino is a classic Italian dessert of wine jelly with whipped cream.",
    "course": "Dessert"
  },
  {
    "name": "Capecchi Cola",
    "price": 3.99,
    "description": "Capecchi Cola is like a Coca Cola, but with a bit more of a Tuscany taste.",
    "course": "Bevanda"
  }
]

### Get all dishes
GET http://localhost:8080/menu/getDishes

### Update dish
POST http://localhost:8080/menu/updateDish
content-type: application/json

{
    "id": 1,
    "name": "Pollo con patate e carciofi",
    "price": 12.99,
    "description": "Pollo con patate e carciofi, is a classic Italian dish of chicken braised in a tomato sauce with onions, garlic, herbs, and sometimes olives and capers. It is traditionally cooked in a casserole dish in the oven, but can also be made in a skillet on the stove top.",
    "course": "Secondo"
}

### Delete dish
POST http://localhost:8080/menu/deleteDish
content-type: application/json

{
  "id": 1
}

### Delete all dishes
POST http://localhost:8080/menu/deleteAllDishes
