
### Add list of dishes
POST http://localhost:8080/menu/addDishes
content-type: application/json

[
    {
    "name": "il Petrone",
    "price": 5.50,
    "description": "panino con prosciutto e mozzarella",
    "imageUrl": "http://www.di.unito.it/~giovanna/gioNew1.jpg",
    "course": "Panino"
  },
  {
    "name": "Coppo di Vino",
    "price": 100.00,
    "description": "vino rosso",
    "imageUrl": null,
    "course": "Bevanda"
  },
  {
    "name": "CapecchiCola",
    "price": 100.00,
    "description": "hoha hola",
    "imageUrl": "http://www.di.unito.it/~capecchi/img/me.jpg",
    "course": "Bevanda"
  }
]

### Get all dishes
GET http://localhost:8080/menu/getDishes
