 name: comand_app_ci_cd_test

 on:
   push:
     branches:
       - order_management

 jobs:

 # Job to build docker images
   build_and_push_to_docker_hub:
     name: Build and push Docker image to Docker Hub
     runs-on: ubuntu-latest

     steps:
       - name: Check out the repo
         uses: actions/checkout@v3

       - name: Set up QEMU dependency
         uses: docker/setup-qemu-action@v1

       - name: Set up Docker Buildx
         uses: docker/setup-buildx-action@v1

       - name: Log in to Docker Hub
         uses: docker/login-action@v2
         with:
           username: scavolini
           password: JQs!LtB4tdRZxNQ

       - name: Extract metadata (tags, labels) for Docker
         id: meta
         uses: docker/metadata-action@v2
         with:
           images: scavolini/comand_app

       - name: Build and push Docker image
         uses: docker/build-push-action@v2
         with:
           context: /home/runner/work/command_app/command_app/order_management/
           push: true
           platforms: linux/arm64/v8
           tags: ${{ steps.meta.outputs.tags }}
           labels: ${{ steps.meta.outputs.labels }}

   compose_raspi:
     name: Execute docker compose on raspberry
     needs: build_and_push_to_docker_hub
     runs-on: self-hosted

     steps:
       - uses: actions/checkout@v3

       - name: Log in to Docker Hub
         uses: docker/login-action@v2
         with:
           username: scavolini
           password: JQs!LtB4tdRZxNQ
        
       - name: Docker compose down and remove old images
         working-directory: /home/pi/compose_test/
         run: docker compose down --rmi local --volumes

       - name: Compose order management
         if: always()
         run: docker compose -f /home/pi/compose_test/docker-compose.yml up --build -d



      
