name: Java CI

on:
  push:
    branches: [ order_management ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'
      - name: Build order management
        run: mvn --batch-mode --update-snapshots package -f /home/runner/work/command_app/command_app/order_management/pom.xml

      - name: Build kitchen
        run: mvn --batch-mode --update-snapshots package -f /home/runner/work/command_app/command_app/kitchen/pom.xml
    
