name: comand_app_ci_cd

on:
  push:
    branches: [ order_management ]

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'
      - name: Build order management
        run: mvn --batch-mode --update-snapshots package

      - name: Build kitchen
        run: mvn --batch-mode --update-snapshots package
    
#   compose:
#     runs-on: ubuntu-latest

#     steps:
#       - uses: actions/checkout@v3
      
#       - name: Compose order management
#         run: docker compose up --build -d
        
#       - name: Compose kitchen
#         run: docker compose up --build -d

      
    
